csv_path = fullfile('experiments','results','data','kMSD_pe_sweep_graySeq_sweeps','summary.csv');
plot_sweeps_from_csv(csv_path, ...
    'SaveDir', fullfile('experiments','results','plots','from_csv'), ...
    'TikZ', true, ...
    'Which', {'runtime','fc'});
